name = "akasha-subscriber"
main = "build/worker/shim.mjs"
send_metrics = false
compatibility_date = "2024-10-01"
workers_dev = false
routes = [{ pattern = "proxy6.minearm.org/*", zone_name = "minearm.org" }]
[build]
command = "worker-build --release"
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



