name = "akasha-subscriber"
main = "build/worker/shim.mjs"
send_metrics = false
compatibility_date = "2024-10-01"
workers_dev = true
routes = [{ pattern = "proxy6.minearm.org/*", zone_name = "minearm.org" }]
[build]
command = "worker-build --release"
